"""Unit tests validating gRPC contract schemas and local serialization.

Verifies that Python datetimes convert cleanly to google.protobuf.Timestamps,
data structures map correctly between CSVs and Protobuf objects, and mock
services bind successfully over gRPC loops.
"""

import datetime
from concurrent import futures
import os
import sys
import unittest
from typing import Generator, List, Tuple
from unittest.mock import MagicMock

# Inject repository paths to allow imports to resolve correctly
ROOT_DIR: str = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
sys.path.insert(0, ROOT_DIR)
sys.path.insert(0, os.path.join(ROOT_DIR, "protos"))

# gRPC stub imports (these will be generated by protoc)
try:
    from google.protobuf.timestamp_pb2 import Timestamp
    import grid_telemetry_pb2 as pb2
    import grid_telemetry_pb2_grpc as pb2_grpc
    import grpc
    GRPC_STUBS_AVAILABLE: bool = True
except ImportError:
    GRPC_STUBS_AVAILABLE = False


def datetime_to_timestamp(dt: datetime.datetime) -> Timestamp:
    """Converts a standard Python datetime to a Protobuf Timestamp.

    Args:
        dt: The naive or timezone-aware datetime instance.

    Returns:
        The initialized Google Protobuf Timestamp object.
    """
    ts = Timestamp()
    ts.FromDatetime(dt)
    return ts


def timestamp_to_datetime(ts: Timestamp) -> datetime.datetime:
    """Converts a Protobuf Timestamp to a standard Python datetime.

    Args:
        ts: The Google Protobuf Timestamp object.

    Returns:
        A naive Python datetime instance in local system time.
    """
    return ts.ToDatetime()


class MockGridTelemetryService(pb2_grpc.GridTelemetryServiceServicer if GRPC_STUBS_AVAILABLE else object):
    """Mock implementation of the GridTelemetryService for contract testing."""

    def EvaluateTelemetrySlice(
        self, request: pb2.TelemetrySlice, context: grpc.ServicerContext
    ) -> pb2.TelemetryResponse:
        """Mock receiver for telemetry slice evaluations.

        Args:
            request: The client-provided phase-aligned TelemetrySlice.
            context: The gRPC call execution context.

        Returns:
            TelemetryResponse indicating success.
        """
        if request.slice_id == "error_test":
            return pb2.TelemetryResponse(success=False, message="Simulated error")
        return pb2.TelemetryResponse(
            success=True, message=f"Received slice {request.slice_id} successfully"
        )

    def GetTelemetryAnalysisStream(
        self, request: pb2.AnalysisRequest, context: grpc.ServicerContext
    ) -> Generator[pb2.AnalysisStreamResponse, None, None]:
        """Mock stream generator for LLM analysis responses.

        Args:
            request: Client request detailing baseline context metadata.
            context: The gRPC call execution context.

        Yields:
            AnalysisStreamResponse tokens representing the LLM generation.
        """
        # 1. Send the initial calculated statistics response
        resp = pb2.AnalysisResponse(
            timestamp=datetime_to_timestamp(datetime.datetime.now()),
            baseline_text=request.baseline_text,
            baseline_timestamp=request.baseline_timestamp,
            summary_text="Mocked Summary...",
            dft_explanation="Mocked DFT...",
            delta_import=1.5,
            delta_export=0.5,
            delta_peak=2.0,
            delta_solar=2.3,
            delta_se_solar=1.5,
            delta_ch_solar=0.8,
            delta_bat_charge=0.5,
            delta_bat_discharge=0.1,
            delta_se_load=1.9,
            expected_temp_max=22.5,
            expected_cloud_cover=35.0,
        )
        yield pb2.AnalysisStreamResponse(initial_analysis=resp)

        # 2. Yield mock summary tokens to simulate server-side Ollama buffering
        yield pb2.AnalysisStreamResponse(summary_token_chunk="This is ")
        yield pb2.AnalysisStreamResponse(summary_token_chunk="a simulated ")
        yield pb2.AnalysisStreamResponse(summary_token_chunk="streaming response.")


@unittest.skipIf(not GRPC_STUBS_AVAILABLE, "Generated gRPC Python stubs are not compiled yet")
class TestGridTelemetryContract(unittest.TestCase):
    """Test suite verifying contract compliance and loopback telemetry routing."""

    def test_timestamp_serialization(self) -> None:
        """Verifies that timestamp conversions operate without rounding errors."""
        now = datetime.datetime.now().replace(microsecond=0)  # Protobuf handles microsecond precision
        pb_ts = datetime_to_timestamp(now)
        converted = timestamp_to_datetime(pb_ts)
        self.assertEqual(now, converted)

    def test_telemetry_request_mapping(self) -> None:
        """Verifies that TelemetryRequest structure represents CSV data correctly."""
        now = datetime.datetime.now()
        req = pb2.TelemetryRequest(
            timestamp=datetime_to_timestamp(now),
            grid_usage_kw=1.450,
            solaredge_pv_kw=2.100,
            solaredge_battery_kw=-0.500,  # Charging
            solaredge_battery_soc=85.5,
            solaredge_load_kw=1.850,
            solaredge_import_kw=0.000,
            solaredge_export_kw=0.250,
            chilicon_pv_kw=0.750,
            chilicon_lifetime_wh=21735.0,
        )

        self.assertEqual(req.grid_usage_kw, 1.450)
        self.assertEqual(req.solaredge_battery_kw, -0.500)
        self.assertEqual(req.chilicon_lifetime_wh, 21735.0)

    def test_telemetry_slice_mapping(self) -> None:
        """Verifies that TelemetrySlice packs requests and spectral metrics correctly."""
        now = datetime.datetime.now()
        req = pb2.TelemetryRequest(
            timestamp=datetime_to_timestamp(now),
            grid_usage_kw=1.200,
        )

        spec = pb2.SpectralMetrics(
            solar_24h_amp=1.50,
            solar_24h_peak_hour=13.5,
            grid_bimodal_ratio=0.45,
            freqs=[1.0, 2.0],
            grid_amp_spec=[0.8, 0.4],
        )

        slice_obj = pb2.TelemetrySlice(
            slice_id="slice_99",
            start_timestamp=datetime_to_timestamp(now),
            end_timestamp=datetime_to_timestamp(now + datetime.timedelta(hours=4)),
            dft_period_hours=24.0,
            readings=[req],
            spectral_metrics=spec,
        )

        self.assertEqual(slice_obj.slice_id, "slice_99")
        self.assertEqual(slice_obj.spectral_metrics.solar_24h_peak_hour, 13.5)
        self.assertEqual(list(slice_obj.spectral_metrics.freqs), [1.0, 2.0])

    def test_loopback_rpc_execution(self) -> None:
        """Spins up a local plaintext loopback server to verify service invocation."""
        server = grpc.server(futures.ThreadPoolExecutor(max_workers=2))
        pb2_grpc.add_GridTelemetryServiceServicer_to_server(MockGridTelemetryService(), server)
        
        # Bind to ephemeral port
        port: int = server.add_insecure_port("localhost:0")
        server.start()

        try:
            # Connect client channel
            channel = grpc.insecure_channel(f"localhost:{port}")
            stub = pb2_grpc.GridTelemetryServiceStub(channel)

            # Test EvaluateTelemetrySlice Unary call
            slice_req = pb2.TelemetrySlice(slice_id="test_rpc_unary")
            resp = stub.EvaluateTelemetrySlice(slice_req)
            self.assertTrue(resp.success)
            self.assertIn("test_rpc_unary", resp.message)

            # Test GetTelemetryAnalysisStream Server-Streaming call
            analysis_req = pb2.AnalysisRequest(
                baseline_timestamp=datetime_to_timestamp(datetime.datetime.now()),
                baseline_text="Starting baseline",
            )
            stream_iter = stub.GetTelemetryAnalysisStream(analysis_req)
            stream_list = list(stream_iter)

            # Assert first message is initial analysis dict
            self.assertEqual(len(stream_list), 4)
            self.assertTrue(stream_list[0].HasField("initial_analysis"))
            self.assertEqual(stream_list[0].initial_analysis.baseline_text, "Starting baseline")
            self.assertEqual(stream_list[0].initial_analysis.delta_import, 1.5)

            # Assert subsequent messages are token strings
            self.assertEqual(stream_list[1].summary_token_chunk, "This is ")
            self.assertEqual(stream_list[3].summary_token_chunk, "streaming response.")

            channel.close()
        finally:
            server.stop(None)


if __name__ == "__main__":
    unittest.main()
