# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from protos import grid_telemetry_pb2 as protos_dot_grid__telemetry__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in protos/grid_telemetry_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GridTelemetryServiceStub:
    """Service to coordinate phase-aligned telemetry ingestion and analysis streaming 
    between the Raspberry Pi (Tier 1 Ingest Node) and NVIDIA Jetson Orin Nano (Tier 2 Gatekeeper).
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.EvaluateTelemetrySlice = channel.unary_unary(
                '/grid.GridTelemetryService/EvaluateTelemetrySlice',
                request_serializer=protos_dot_grid__telemetry__pb2.TelemetrySlice.SerializeToString,
                response_deserializer=protos_dot_grid__telemetry__pb2.TelemetryResponse.FromString,
                _registered_method=True)
        self.GetTelemetryAnalysisStream = channel.unary_stream(
                '/grid.GridTelemetryService/GetTelemetryAnalysisStream',
                request_serializer=protos_dot_grid__telemetry__pb2.AnalysisRequest.SerializeToString,
                response_deserializer=protos_dot_grid__telemetry__pb2.AnalysisStreamResponse.FromString,
                _registered_method=True)


class GridTelemetryServiceServicer:
    """Service to coordinate phase-aligned telemetry ingestion and analysis streaming 
    between the Raspberry Pi (Tier 1 Ingest Node) and NVIDIA Jetson Orin Nano (Tier 2 Gatekeeper).
    """

    def EvaluateTelemetrySlice(self, request, context):
        """Phase-aligned telemetry batch handover from Tier 1 to Tier 2
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTelemetryAnalysisStream(self, request, context):
        """Server-streaming call to stream Ollama/Gemma generated tokens back to Pi Kiosk
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GridTelemetryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'EvaluateTelemetrySlice': grpc.unary_unary_rpc_method_handler(
                    servicer.EvaluateTelemetrySlice,
                    request_deserializer=protos_dot_grid__telemetry__pb2.TelemetrySlice.FromString,
                    response_serializer=protos_dot_grid__telemetry__pb2.TelemetryResponse.SerializeToString,
            ),
            'GetTelemetryAnalysisStream': grpc.unary_stream_rpc_method_handler(
                    servicer.GetTelemetryAnalysisStream,
                    request_deserializer=protos_dot_grid__telemetry__pb2.AnalysisRequest.FromString,
                    response_serializer=protos_dot_grid__telemetry__pb2.AnalysisStreamResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'grid.GridTelemetryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('grid.GridTelemetryService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GridTelemetryService:
    """Service to coordinate phase-aligned telemetry ingestion and analysis streaming 
    between the Raspberry Pi (Tier 1 Ingest Node) and NVIDIA Jetson Orin Nano (Tier 2 Gatekeeper).
    """

    @staticmethod
    def EvaluateTelemetrySlice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grid.GridTelemetryService/EvaluateTelemetrySlice',
            protos_dot_grid__telemetry__pb2.TelemetrySlice.SerializeToString,
            protos_dot_grid__telemetry__pb2.TelemetryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTelemetryAnalysisStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/grid.GridTelemetryService/GetTelemetryAnalysisStream',
            protos_dot_grid__telemetry__pb2.AnalysisRequest.SerializeToString,
            protos_dot_grid__telemetry__pb2.AnalysisStreamResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
